// Generated by Supabase CLI: supabase gen types typescript --linked
// Run this command after applying migrations to keep types in sync

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          name: string;
          role: "admin" | "team_manager";
          created_at: string;
        };
        Insert: {
          id: string;
          name: string;
          role: "admin" | "team_manager";
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          role?: "admin" | "team_manager";
          created_at?: string;
        };
      };
      seasons: {
        Row: {
          id: string;
          name: string;
          start_date: string;
          end_date: string;
          is_active: boolean;
          status: "setup" | "group_stage" | "playoffs" | "finished";
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          start_date: string;
          end_date: string;
          is_active?: boolean;
          status?: "setup" | "group_stage" | "playoffs" | "finished";
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          start_date?: string;
          end_date?: string;
          is_active?: boolean;
          status?: "setup" | "group_stage" | "playoffs" | "finished";
          created_at?: string;
        };
      };
      teams: {
        Row: {
          id: string;
          name: string;
          shield_url: string | null;
          primary_color: string | null;
          secondary_color: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          shield_url?: string | null;
          primary_color?: string | null;
          secondary_color?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          shield_url?: string | null;
          primary_color?: string | null;
          secondary_color?: string | null;
          created_at?: string;
        };
      };
      season_teams: {
        Row: {
          id: string;
          season_id: string;
          team_id: string;
          manager_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          season_id: string;
          team_id: string;
          manager_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          season_id?: string;
          team_id?: string;
          manager_id?: string | null;
          created_at?: string;
        };
      };
      groups: {
        Row: {
          id: string;
          season_id: string;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          season_id: string;
          name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          season_id?: string;
          name?: string;
          created_at?: string;
        };
      };
      group_teams: {
        Row: {
          id: string;
          group_id: string;
          season_team_id: string;
        };
        Insert: {
          id?: string;
          group_id: string;
          season_team_id: string;
        };
        Update: {
          id?: string;
          group_id?: string;
          season_team_id?: string;
        };
      };
      players: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          photo_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          first_name: string;
          last_name: string;
          photo_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          photo_url?: string | null;
          created_at?: string;
        };
      };
      player_registrations: {
        Row: {
          id: string;
          player_id: string;
          season_team_id: string;
          jersey_number: number | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          player_id: string;
          season_team_id: string;
          jersey_number?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          player_id?: string;
          season_team_id?: string;
          jersey_number?: number | null;
          is_active?: boolean;
          created_at?: string;
        };
      };
      matches: {
        Row: {
          id: string;
          season_id: string;
          phase: "group" | "upper_playoff" | "lower_playoff";
          group_id: string | null;
          round: number;
          home_team_id: string | null;
          away_team_id: string | null;
          scheduled_date: string | null;
          status: "pending" | "played";
          home_score: number | null;
          away_score: number | null;
          home_penalties: number | null;
          away_penalties: number | null;
          next_match_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          season_id: string;
          phase: "group" | "upper_playoff" | "lower_playoff";
          group_id?: string | null;
          round: number;
          home_team_id?: string | null;
          away_team_id?: string | null;
          scheduled_date?: string | null;
          status?: "pending" | "played";
          home_score?: number | null;
          away_score?: number | null;
          home_penalties?: number | null;
          away_penalties?: number | null;
          next_match_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          season_id?: string;
          phase?: "group" | "upper_playoff" | "lower_playoff";
          group_id?: string | null;
          round?: number;
          home_team_id?: string | null;
          away_team_id?: string | null;
          scheduled_date?: string | null;
          status?: "pending" | "played";
          home_score?: number | null;
          away_score?: number | null;
          home_penalties?: number | null;
          away_penalties?: number | null;
          next_match_id?: string | null;
          created_at?: string;
        };
      };
      match_events: {
        Row: {
          id: string;
          match_id: string;
          player_id: string;
          season_team_id: string;
          type: "goal" | "yellow_card" | "red_card";
          minute: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          match_id: string;
          player_id: string;
          season_team_id: string;
          type: "goal" | "yellow_card" | "red_card";
          minute?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          match_id?: string;
          player_id?: string;
          season_team_id?: string;
          type?: "goal" | "yellow_card" | "red_card";
          minute?: number | null;
          created_at?: string;
        };
      };
      sanctions: {
        Row: {
          id: string;
          player_id: string;
          season_id: string;
          triggering_match_id: string;
          reason: "yellow_accumulation" | "red_card" | "additional";
          matches_suspended: number;
          matches_served: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          player_id: string;
          season_id: string;
          triggering_match_id: string;
          reason: "yellow_accumulation" | "red_card" | "additional";
          matches_suspended: number;
          matches_served?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          player_id?: string;
          season_id?: string;
          triggering_match_id?: string;
          reason?: "yellow_accumulation" | "red_card" | "additional";
          matches_suspended?: number;
          matches_served?: number;
          is_active?: boolean;
          created_at?: string;
        };
      };
      publications: {
        Row: {
          id: string;
          title_eu: string;
          title_es: string;
          body_eu: string;
          body_es: string;
          author_id: string;
          published_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          title_eu: string;
          title_es: string;
          body_eu: string;
          body_es: string;
          author_id: string;
          published_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          title_eu?: string;
          title_es?: string;
          body_eu?: string;
          body_es?: string;
          author_id?: string;
          published_at?: string;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: "sanction" | "result" | "publication" | "suspension_warning";
          title: string;
          body: string;
          is_read: boolean;
          entity_type: string | null;
          entity_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: "sanction" | "result" | "publication" | "suspension_warning";
          title: string;
          body: string;
          is_read?: boolean;
          entity_type?: string | null;
          entity_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: "sanction" | "result" | "publication" | "suspension_warning";
          title?: string;
          body?: string;
          is_read?: boolean;
          entity_type?: string | null;
          entity_id?: string | null;
          created_at?: string;
        };
      };
    };
  };
};
